stages:
  - build

.build_meson: &build_meson
  - mkdir build-meson
  - meson . build-meson
  - ninja-build -C build-meson

build_fedora:
  stage: build
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  before_script:
    - dnf builddep -y *.spec
  script:
    - *build_meson

build_centos8:
  stage: build
  image: registry.gitlab.com/kraxel/rpm-package-builder:centos8
  before_script:
    - dnf builddep -y *.spec
  script:
    - *build_meson

