stages:
  - build

.builddep_dnf: &builddep_dnf
  - dnf install -y 'dnf-command(builddep)'
  - dnf builddep -y *.spec

.build_meson: &build_meson
  - mkdir build-meson
  - meson . build-meson
  - ninja-build -C build-meson

build_fedora:
  stage: build
  image: fedora:latest
  before_script:
    - *builddep_dnf
  script:
    - *build_meson

build_centos8:
  stage: build
  image: centos:8
  before_script:
    - dnf install -y 'dnf-command(config-manager)'
    - dnf config-manager --set-enabled PowerTools
    - *builddep_dnf
  script:
    - *build_meson

