stages:
  - build
  - rpms
  - repo

.build_meson: &build_meson
  - mkdir build-meson
  - meson . build-meson
  - ninja-build -C build-meson

build_fedora:
  stage: build
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  before_script:
    - dnf builddep -y *.spec
  script:
    - *build_meson

build_centos8:
  stage: build
  image: registry.gitlab.com/kraxel/rpm-package-builder:centos8
  before_script:
    - dnf builddep -y *.spec
  script:
    - *build_meson

build_centos7:
  stage: build
  image: registry.gitlab.com/kraxel/rpm-package-builder:centos7
  before_script:
    - yum-builddep -y *.spec
  script:
    - *build_meson

tito_fedora:
  stage: rpms
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  before_script:
    - dnf builddep -y *.spec
  script:
    - tito build --test --rpm --output rpms-fedora
    - createrepo rpms-fedora
  artifacts:
    paths:
      - rpms-fedora/

pages:
  stage: repo
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  dependencies:
    - tito_fedora
  script:
    - mkdir public
    - mv rpms-fedora public/fedora
    - dnf install -y tree
    - tree -H . public > index.html
    - mv index.html public
  artifacts:
    paths:
      - public/
