stages:
  - build

.builddep_dnf: &builddep_dnf
  - dnf install -y 'dnf-command(builddep)'
  - dnf builddep -y *.spec

build_fedora:
  stage: build
  image: fedora:latest
  script:
    - *builddep_dnf
    - mkdir build-meson
    - meson . build-meson
    - ninja-build -C build-meson 
