stages:
  - build
  - rpms
  - repo

include:
  - project: 'kraxel/rpm-package-builder'
    file: 'gitlab-ci-build-meson.yml'

include:
  - project: 'kraxel/rpm-package-builder'
    file: 'gitlab-ci-rpms-tito.yml'

boot-aarch64:
  stage: build
  rules:
    - if: '$BUILD_AARCH64 == "yes"'
  trigger:
    project: kraxel/ec2-init-scripts
    branch: boot-aarch64
