.TH GLOAD 1 "(c) 2019 Gerd Hoffmann" "GLOAD" "load monitor"
\#
\#
.SH NAME
gload - load monitor
\#
\#
.SH SYNOPSIS
.TP
\fBgload
\#
\#
.SH DESCRIPTION
.BR gload
is a load average monitor, inspired by xload.
\#
\#
.SH OPTIONS
No config options yet.
\#
\#
.SH "SEE ALSO"
.BR xload(1)
\#
\#
.SH AUTHOR
Gerd Hoffmann
.BR <gerd@kraxel.org>
