.TH GTERM 1 "(c) 2019 Gerd Hoffmann" "GTERM" "terminal application"
\#
\#
.SH NAME
gterm - terminal application
\#
\#
.SH SYNOPSIS
.TP
\fBgterm\fP [\fIoptions\fP]
\#
\#
.SH DESCRIPTION
.BR gterm
is a terminal application.  Command line options are compatible with
xterm, not all xterm options are actually implemented though.
\#
\#
.SH OPTIONS
.TP
.B -e
Command line to run within the terminal.  All arguments following this
one are passed to the command started and will not be parsed, so this
should be last on your command line.  If not specified a shell is
started.
.TP
.BI -fa " face"
The font face to use.
.br
Config file key: faceName.
.TP
.BI -fs " size"
The font size to use.
.br
Config file key: faceSize.
.br
Only in the config file: faceSize1 .. faceSize6, they will be added as
alternative font sizes to the popup menu.
.TP
.BI -geometry " WxH"
The width and height of the terminal window (in columns/rows, not pixels).
.br
Config file key: geometry.
.TP
.BI -title " text"
Set the window title.
.br
Config file key: title.
.TP
.BI -T " text"
Shortcut for -title.
.TP
.B -bc
Enable cursor blinking.
.br
Config file key: cursorBlink.
.TP
.B +bc
Disable cursor blinking.
.TP
.BI -cr " color"
Set the cursor color
.br
Config file key: cursorColor.
.TP
.BI -fg " color"
Set the foreground color
.br
Config file key: foreground.
.TP
.BI -fg " color"
Set the background color
.br
Config file key: background.
.TP
.BI -name " profile"
Set profile.  gterm will read settings from a [profile] section in the
config file (if present).  This mimics xterm's behavior of changing
application name / application class when reading resources, so you
could have different config sets in ~/.Xdefaults which are selected
that way.
.TP
.BI -class " profile"
Alias for -name.
.TP
.B -vb
Disable audible bell (xterm enables visual bell instead, but vte
widget doesn't support that).
.br
Config file key: visualBell.
.TP
.B +vb
Enable audible bell.
\#
\#
.SH "CONFIG FILE"
.BR gterm
reads the configuration from the 
.BR ~/.config/gterm.conf
config file.
A "[default]" section holds the config options.
Example:
.P
.in +4n
[default]
.br
faceName=Terminus
.br
faceSize=12
.in
.P
This has the same effect this ~/.Xdefaults snippet has for xterm:
.P
.in +4n
XTerm.vt100*faceName: Terminus
.br
XTerm.vt100*faceSize: 12
.in
.P
\#
\#
.SH "SEE ALSO"
.BR xterm(1)
\#
\#
.SH AUTHOR
Gerd Hoffmann
.BR <gerd@kraxel.org>
